Repository juicedata/juicefs, pull requests merged in 2023-12, with the labels that each got.

#4281 Docs: add `sync` command metrics
  docs/en/reference/p8s_metrics.md
  docs/zh_cn/reference/p8s_metrics.md
Labels: kind/documentation

#4279 object/jfsobj: fix bug with opening files instead of creating them
  cmd/object.go
Labels: backport-1.1

#4286 sync: fix symlink with jfs://
  cmd/object_test.go
  pkg/fs/fs.go
  sdk/java/libjfs/main.go
Labels: backport-1.1

#4270 cmd/sync: don't create dir when src is not exist
  pkg/object/file.go
Labels: backport-1.1

#4292 cmd/sync: don't create dir when create sftp endpoint.
  pkg/object/sftp.go
Labels: backport-1.1

#4299 sdk/java: fix guid update
  sdk/java/libjfs/guid.go
  sdk/java/libjfs/main.go
Labels: backport-1.0, backport-1.1
