Repository juicedata/juicefs, pull requests merged in 2024-04, with the labels that each got.

#4762 cmd/dump: fix DumpedCounters to prevent unexpected panics
  pkg/meta/dump.go
Labels: kind/bug

#4763 cmd/warmup: periodically refresh cache bytes progress
  cmd/warmup.go
  pkg/vfs/fill.go
Labels: kind/enhancement

#4793 Docs: fix encryption image
  docs/en/guide/gateway.md
  docs/en/images/encryption.png
  docs/en/security/posix_acl.md
  docs/zh_cn/images/encryption.png
Labels: kind/documentation
