Repository juicedata/juicefs, pull requests merged in 2024-08, with the labels that each got.

#5051 refactor adopter list, remove environment column
  .github/workflows/check-doc.yaml
  docs/zh_cn/community/adopters.md
Labels: kind/documentation

#5046 sync: fixed bandwidth limit bug when streaming
  pkg/sync/sync.go
Labels: backport-1.1, backport-1.2

#5068 cmd/gc: fix the issue that objects may be deleted by mistake in large systems
  cmd/gc.go
Labels: backport-1.1, backport-1.2

#5069 quota: fixed a bug where hardlink's quota update in the same directory was incorrect
  pkg/meta/quota.go
Labels: backport-1.2

#5084 set the upload flag to false if the upload fails
  pkg/chunk/cached_store.go
Labels: backport-1.1, backport-1.2

#5083 fix invalid file matching regular expressions
  pkg/chunk/disk_cache.go
  pkg/chunk/disk_cache_test.go
Labels: backport-1.1, backport-1.2

#5103 Docs: refactor sync filtering doc
  docs/en/guide/sync.md
  docs/en/images/layered-filtering.png
  docs/en/images/one-time-filtering.png
  docs/en/images/sync-full-path-filtering-mode-flow-chart.svg
  docs/en/images/sync-layer-by-layer-filtering-mode-flow-chart.svg
  docs/en/reference/command_reference.mdx
  docs/zh_cn/guide/sync.md
  docs/zh_cn/images/sync-full-path-filtering-mode-flow-chart.svg
  docs/zh_cn/images/sync-hierarchical-filtration.svg
  docs/zh_cn/images/sync-layer-by-layer-filtering-mode-flow-chart.svg
  docs/zh_cn/images/sync-single-layer-filtration.svg
  docs/zh_cn/reference/command_reference.mdx
Labels: kind/documentation

#5108 fix panic build with go1.23
  go.mod
  go.sum
Labels: backport-1.2
