Repository juicedata/juicefs, pull requests merged in 2024-01, with the labels that each got.

#4337 cmd/compact: add new compact cmd, used for specific path
  .gitignore
  cmd/compact_test.go
  cmd/compact_unix.go
  cmd/compact_windows.go
  cmd/main.go
  go.mod
  go.sum
  pkg/meta/base.go
  pkg/meta/context.go
  pkg/meta/interface.go
  pkg/vfs/internal.go
Labels: kind/feature

#4370 Feat: cmd-warmup add option "check" and "evict"
  cmd/warmup.go
  pkg/chunk/cached_store.go
  pkg/chunk/cached_store_test.go
  pkg/chunk/chunk.go
  pkg/vfs/fill.go
  pkg/vfs/fill_test.go
  pkg/vfs/internal.go
  pkg/vfs/vfs_test.go
Labels: kind/feature

#4388 cmd/bench: fix bench progress bar
  cmd/bench.go
Labels: backport-1.1

#4390 cmd/sync: fix the dst password is not removed
  cmd/main.go
  cmd/sync.go
Labels: backport-1.0, backport-1.1
